# Generated by Django 3.2.8 on 2021-11-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phonenumber', models.CharField(blank=True, max_length=12, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary')], default='Male', max_length=10)),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction (200 Words or less)')),
                ('languages', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='English', max_length=25)),
                ('education', models.CharField(blank=True, choices=[('None', 'None'), ('CIN', 'Currently Enrolled In College'), ('AS', 'Associate'), ('TECH', 'Technical Certification'), ('BAS', 'BA/BS/Etc . . .'), ('MA', 'MA/MS/Etc...'), ('ED', 'Education Specialist/6th Year/Etc . . .'), ('EDD', 'ED.D/PH.D/Etc . . .')], default='HS', max_length=60)),
                ('major', models.CharField(blank=True, max_length=20, verbose_name='Major (If Applicable)')),
                ('minor', models.CharField(blank=True, max_length=20, verbose_name='Minor (If Applicable)')),
                ('experience', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, verbose_name='Are You A Certified Teacher?')),
                ('statecert', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AR', 'AR'), ('AZ', 'AZ'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DC', 'DC'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('IA', 'IA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('MA', 'MA'), ('MD', 'MD'), ('ME', 'ME'), ('MI', 'MI'), ('MN', 'MN'), ('MO', 'MO'), ('MS', 'MS'), ('MT', 'MT'), ('NC', 'NC'), ('NE', 'NE'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NV', 'NV'), ('NY', 'NY'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WI', 'WI'), ('WV', 'WV'), ('WY', 'WY'), ('None', 'None')], default='None', max_length=5, verbose_name='Please Choose The State You Are Certified In:')),
                ('phonicsex', models.CharField(blank=True, choices=[('Fundations', 'Fundations'), ('Fountas & Pinnell Literacy', 'Fountas & Pinnell Literacy'), ('Lucy Calkins Units Of Study For Teaching Phonics', 'Lucy Calkins Units Of Study For Teaching Phonics'), ('Bridge The Gap Intervention', 'Bridge The Gap Intervention'), ('Words Their Way', 'Words Their Way'), ('Lalilo', 'Lalilo'), ('The Heggerty Curriculum', 'The Heggerty Curriculum'), ('Orton Gillingham Approach', 'Orton Gillingham Approach'), ('Phonics First', 'Phonics First'), ('Other', 'Other')], max_length=200, verbose_name='Choose Any Phonics Programs You Have Experience With:')),
                ('employment', models.CharField(blank=True, choices=[('Fulltime', 'Fulltime'), ('Part Time', 'Part Time'), ('College Student', 'College Student'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=20)),
                ('curremployment', models.CharField(blank=True, max_length=30)),
                ('employer', models.CharField(blank=True, max_length=20, verbose_name='Employer')),
                ('employeraddress', models.CharField(blank=True, max_length=30, verbose_name='Employer Address')),
                ('currreference', models.CharField(blank=True, max_length=20, verbose_name='Supervisor/Reference Contact Information:')),
                ('teachercharacteristics', models.TextField(blank=True, max_length=200, verbose_name='What Characteristics Make A Good Teacher: (200 Words or less)')),
                ('abilitiesquestion', models.TextField(blank=True, max_length=200, verbose_name='How Would You Address A Range Of Abilities In Your Classroom: (200 Words or less)')),
                ('availability', models.CharField(blank=True, choices=[('AM', 'Part Time AM'), ('PM', 'Full Time PM')], max_length=20, verbose_name='Choose Your Availability:')),
            ],
        ),
    ]
