# Generated by Django 3.2.8 on 2021-11-05 06:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.AddField(
            model_name='tutor',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='English', max_length=29),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phonicsex',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fundations', 'Fundations'), ('Fountas & Pinnell Literacy', 'Fountas & Pinnell Literacy'), ('Lucy Calkins Units Of Study For Teaching Phonics', 'Lucy Calkins Units Of Study For Teaching Phonics'), ('Bridge The Gap Intervention', 'Bridge The Gap Intervention'), ('Words Their Way', 'Words Their Way'), ('Lalilo', 'Lalilo'), ('The Heggerty Curriculum', 'The Heggerty Curriculum'), ('Orton Gillingham Approach', 'Orton Gillingham Approach'), ('Phonics First', 'Phonics First'), ('Other', 'Other')], max_length=207, verbose_name='Choose Any Phonics Programs You Have Experience With:'),
        ),
    ]
