# Generated by Django 3.2.8 on 2021-11-07 03:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20211105_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='abilitiesquestion',
            field=models.TextField(blank=True, max_length=200, verbose_name='How Would You Address A Range Of Abilities In Your Classroom: (200 Words or Less)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='curremployment',
            field=models.CharField(blank=True, max_length=30, verbose_name='Current or Most Recent Job Title (If Applicable)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='currreference',
            field=models.CharField(blank=True, max_length=20, verbose_name='Supervisor/Reference Contact Information (If Applicable)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='education',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('CIN', 'Currently Enrolled In College'), ('AS', "Associate's Degree"), ('TECH', 'Technical Certification'), ('BAS', "Bachelor's Degree"), ('MA', "Master's Degree"), ('ED', 'Education Specialist/6th Year/Etc . . .'), ('EDD', 'Doctorate or Higher')], default='None', max_length=60, verbose_name='Highest Level of Education'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='employer',
            field=models.CharField(blank=True, max_length=30, verbose_name='Employer (If Applicable)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='employeraddress',
            field=models.CharField(blank=True, max_length=30, verbose_name='Employer Address (If Applicable)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='employment',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('College Student', 'College Student'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=20, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='None', max_length=29),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='statecert',
            field=models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AR', 'AR'), ('AZ', 'AZ'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DC', 'DC'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('IA', 'IA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('MA', 'MA'), ('MD', 'MD'), ('ME', 'ME'), ('MI', 'MI'), ('MN', 'MN'), ('MO', 'MO'), ('MS', 'MS'), ('MT', 'MT'), ('NC', 'NC'), ('NE', 'NE'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NV', 'NV'), ('NY', 'NY'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WI', 'WI'), ('WV', 'WV'), ('WY', 'WY'), ('None', 'None')], default='None', max_length=5, verbose_name='Please Choose The State In Which You are Certified:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='teachercharacteristics',
            field=models.TextField(blank=True, max_length=200, verbose_name='What Characteristics Make A Good Teacher: (200 Words or Less)'),
        ),
    ]
