# Generated by Django 3.2.8 on 2021-11-08 05:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20211108_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='phonenumber',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone Number'),
        ),
    ]
