# Generated by Django 3.2.8 on 2021-11-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20211109_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
