# Generated by Django 3.2.8 on 2021-11-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_alter_tutor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='availability',
            field=models.CharField(blank=True, choices=[('AM', 'Part Time AM'), ('PM', 'Part Time PM'), ('Full Time', 'Full Time (AM and PM)')], max_length=20, verbose_name='Choose Your Availability:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='currreference',
            field=models.CharField(blank=True, max_length=60, verbose_name='Supervisor/Reference Contact Information (If Applicable)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='education',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('College Student', 'Currently Enrolled In College'), ('A.A./A.S.', "Associate's Degree"), ('Technical Certification', 'Technical Certification'), ('B.A./B.S.', "Bachelor's Degree"), ('M.A./M.S./M.Ed.', "Master's Degree"), ('Ed.S.', 'Education Specialist/6th Year/Etc . . .'), ('Ed.D./Ph.D.', 'Doctorate or Higher')], default='None', max_length=60, verbose_name='Highest Level of Education'),
        ),
    ]
