# Generated by Django 3.2.8 on 2021-11-30 23:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_auto_20211122_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='education',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('None', 'None'), ('College Student', 'Currently Enrolled In College'), ('A.A./A.S.', "Associate's Degree"), ('Technical Certification', 'Technical Certification'), ('B.A./B.S.', "Bachelor's Degree"), ('M.A./M.S./M.Ed.', "Master's Degree"), ('Ed.S.', 'Education Specialist/6th Year/Etc . . .'), ('Ed.D./Ph.D.', 'Doctorate')], max_length=98, verbose_name='Level of Education (Please Select All That Apply):'),
        ),
    ]
