# Generated by Django 3.2.8 on 2021-12-06 01:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_alter_tutor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='otherphonics',
            field=models.TextField(blank=True, max_length=500, verbose_name='If You Selected "Other," List Other Phonics Programs Here:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish')], default='None', max_length=15, verbose_name='Languages Spoken Fluently'),
        ),
    ]
