# Generated by Django 3.2.8 on 2021-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_alter_tutor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name=''),
        ),
    ]
